git:
 submodules: false

language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: RID=ubuntu
    - os: linux
      dist: trusty
      sudo: required
      env: RID=centos
    - os: osx
      env: RID=osx

branches:
 only:
   - master
   - /^maint.*/

before_install:
 - date -u
 - uname -a
 - env | grep -v "BINTRAY_API_KEY" | sort
 - git submodule update --init

install: true

script: ./build.libgit2.sh

after_success: ./uploadbinaries.sh
